### ISSUE TITLE
third crashing

### ISSUE THREAD

**Issue by wboeke** [howerj/third#1]
Hello,
The startup file for third is third.fth. However, after 3 statements in this file there is an exit statement. That's not for nothing: the first statement after the exit makes the program crash.
I tried fo find the course, but couldn'd find it. Could you please look at this?

**Comment by howerj** [comment]
If I run it I have no problems, can you give me more information; what platform you are running on, 32/64 bit, how it is crashing, what were you trying to do?

There is no course, but if you mean the original source, then it is from here:

https://www.ioccc.org/years.html

Under the entry "buzzard.2".

Thanks

**Comment by wboeke** [comment]
My issue was from the code in howerj/third. And as I wrote before, the 'exit' statement was in the original third.fth file.
My platform is 64bit, Fedora, compiler gcc or clang.
The error message after: cat third.fth - | ./third
is: Unknown instruction
This instruction appears to have value  656
So it's not a real crash, but an exit because of an error. This is a pity, because this is such a nice super small program.

**Comment by howerj** [comment]
I've compile with tcc, clang, and gcc, all on a 64-bit platform, Ubuntu, using the same command and I get no errors, just the prompt. Do you get any warnings when compiling, I only get one about fscanf. Which versions of clang/gcc are you using?
("clang version 10.0.0-4ubuntu1, Target: x86_64-pc-linux-gnu" and "gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)" for me.

The third.fth file has not been modified in anyway?

**Comment by howerj** [comment]
I get a similar error message if I feed the binary instead of the source into the program, which obviously isn't going to work.

**Comment by wboeke** [comment]
This is my problem:
In this repo, click 'Goto file'
Click on third.fth
line 6: exit
So the file is only executed until line 6
If you run line 8 the program will exit because of an error. So all the interesting stuff after line 6 is there in vain. And that is my problem.

**Comment by howerj** [comment]
Unfortunately I haven't been able to reproduce the issue at all, it works on all platforms I have tried it on including Windows 32/64 bit. I always get the "Welcome to third." followed by "Ok." printed out.

Interestingly I can get it to fail with the instruction being '656' if I delete the "exit" on that line, but I wouldn't expect it to work at all then anyway.

It would still help to know which compiler versions you are using, your platform (x86_64, ARM, ...) and what warnings you get when compiling "third".

**Comment by wboeke** [comment]
Let me state it otherwise.
Remove the line with 'exit' from third.fth 
Then run: cat third.fth - | ./third
See wat happens. You will get output:  Unknown instruction

**Comment by howerj** [comment]
Yeah...of course, that exit is meant to be there (it compiles an exit into the definition of ';', it does not exit the program), the program will not work without it.

**Comment by wboeke** [comment]
Your last comment did it! third works!
I added a prompt, and tried to create a recursive function:
: fib dup 1 > if dup 1 - fib swap 2 - fib + else drop 1 then ;
What is missing in third is probably only the '>' operator, I am trying to add it.
Thanks for your answers!

**Comment by howerj** [comment]
That's great, I'll close this then!
