### ISSUE TITLE
The " operator

### ISSUE THREAD

**Issue by wboeke** [howerj/third#2]
I cannot get the " word working. What is wrong with the next statements?

: test " hello" print ;
test

The result:
hello��@ B#L)*&Q-S15W	9Y ....

Apparently some loop does not terminate, but I cannot find a solution.

**Comment by howerj** [comment]
`: test " hello" ;` works, you should not have a "print" there.

**Comment by wboeke** [comment]
Sorry to reopen...
Of course I tried this already. If I enter 'test', then nothing happens however.
When I accidently find a solution, I'll report it to you.

**Comment by howerj** [comment]
It's because the output buffer is not being flushed until you call `cr` (or it gets full), try:
```

: test " hello" ;
test cr

```
If you want you could modify `third.c` to call `fflush(tobj->output);` after `fputc`, but it's working as intended.
